name: Telnyx Autotests Cypress+Cucumber
on:
  push:
    branches: [main]
jobs:
  Run_test:
    runs-on: Windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22
          cache: "npm"


      - name: install all dependencies
        run: npm i


      - name: run test
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        run: npm run cypress:run


      - name: Generate reports
        if: always()
        run: npm run cypress:report


      - name: Upload artifact cucumber-report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cucumber-report
          path: ./reports/cucumber-htmlreport


      - name: Deploy to pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GH_PAT}}
          publish_branch: test-reports
          publish_dir: reports/cucumber-htmlreport/