name: Telnyx Autotests

on:
  push:
    branches:
      - LQB-23
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: E2E Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Clean reports directory
        run: |
          rm -rf cypress/reports
          mkdir -p cypress/reports/html

      - name: Run Cypress tests and generate Mochawesome report
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          npm run test || true
          find cypress/reports -name '*.json' -size +0c -exec npx mochawesome-merge {} + > cypress/reports/mochareport.json || echo "⚠️ Failed to merge reports, skipping..."
          npx marge cypress/reports/mochareport.json --reportDir cypress/reports/html --inline || echo "⚠️ Failed to generate HTML report"

      - name: Upload All Cypress Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-full-report
          path: |
            cypress/reports/
            cypress/videos/
            cypress/screenshots/
          retention-days: 1

      - name: Deploy HTML report to GitHub Pages
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: test-reports
          folder: cypress/reports/html
          clean: true
          token: ${{ secrets.GH_PAT }}
