name: Telnyx Autotests cypress+cucumber

on:
  push:
    branches:
      - LQB-23
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: E2E Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci


      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        with:
          browser: chrome
          headed: false
          record: false
          command: npx cypress run --reporter mochawesome --reporter-options overwrite=false,html=false,json=true,reportDir=cypress/reports


      - name: Generate Mochawesome HTML report
        if: always()
        run: |
          mkdir -p cypress/reports/html
          if compgen -G "cypress/reports/*.json" > /dev/null; then
            npx mochawesome-merge cypress/reports/*.json > cypress/reports/output.json
            npx marge cypress/reports/output.json --reportDir cypress/reports/html --reportFilename index.html
          else
            echo "No JSON reports found. Skipping merge."
          fi



      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: |
            cypress/videos/
            cypress/screenshots/
            cypress/reports/


      - name: Deploy HTML report to GitHub Pages
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: test-reports
          folder: cypress/reports/html
          clean: true
          token: ${{ secrets.GH_PAT }}